CalendarWorkSchedule/Controllers/CalendarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CalendarWorkSchedule.Models;

namespace CalendarWorkSchedule.Controllers
{
    public class CalendarController : Controller
    {

        // GET: Calendar
        public ActionResult Index()
        {
            return View();
        }



        public JsonResult GetEvents()
        {
            using (ApplicationDbContext dc = new ApplicationDbContext())
            {
                dc.Configuration.LazyLoadingEnabled = false;
                var events = dc.Events.ToList();
                return new JsonResult { Data = events, JsonRequestBehavior = JsonRequestBehavior.AllowGet };


            }

        }

        [HttpPost]
        public JsonResult SaveEvent(Event e)
        {
            var status = false;
            using (ApplicationDbContext dc = new ApplicationDbContext())
            {
                if (e.EventID > 0)
                {
                    var v = dc.Events.Where(a => a.EventID == e.EventID).FirstOrDefault();
                    if (v != null)
                    {
                        v.Subject = e.Subject;
                        v.Start = e.Start;
                        v.End = e.End;
                        v.Description = e.Description;
                        v.IsFullDay = e.IsFullDay;
                        v.ThemeColor = e.ThemeColor;

                    }

                }
                else
                {
                    dc.Events.Add(e);
                }
                dc.SaveChanges();
                status = true;
            }
            return new JsonResult { Data = new { status = status } };
        }

        [HttpPost]
        public JsonResult DeleteEvent(int eventId)
        {
            var status = false;
            using (ApplicationDbContext dc = new ApplicationDbContext())
            {
                var v = dc.Events.Where(a => a.EventID == eventId).FirstOrDefault();
                if (v != null)
                {
                    dc.Events.Remove(v);
                    dc.SaveChanges();
                    status = true;
                }

            }
            return new JsonResult { Data = new { status = status } };

        }

    }
}

CalendarWorkSchedule/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CalendarWorkSchedule.Models;

namespace CalendarWorkSchedule.Controllers
{
    public class EventsController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        // GET: Events
        public ActionResult Index()
        {
            var listevents = db.Events.ToList();
            return View(listevents);
        }

        public ActionResult Create()
        {

            return View();
        }
        [HttpPost]
        public ActionResult Create(Event events)
        {
            if (ModelState.IsValid)
            {
                db.Events.Add(events);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(events);
        }

        public ActionResult SingleEvent(long id)
        {
            var eventId = db.Events.Find(id);
            return View(eventId);
        }

        [HttpPost]
        public ActionResult SingleEvent(long id, Comment newComment)
        {
            if (ModelState.IsValid)
            {
                newComment.Event = db.Events.Find(id);
                db.Comment.Add(newComment);
                db.SaveChanges();
                return RedirectToAction("SingleEvent", new { Id = id });
            }
            return SingleEvent(id);

        }
    }
}

CalendarWorkSchedule/Controllers/TasksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CalendarWorkSchedule.Models;

namespace CalendarWorkSchedule.Controllers
{
    public class TasksController : Controller
    {
        // GET: Tasks
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetTasks()
        {
            using (ApplicationDbContext dm = new ApplicationDbContext())
            {
                dm.Configuration.LazyLoadingEnabled = false;
                var tasks = dm.Events.ToList();
                return new JsonResult { Data = tasks, JsonRequestBehavior = JsonRequestBehavior.AllowGet };


            }

        }

        public ActionResult Test()
        {
            return View();
        }
    }
}

CalendarWorkSchedule/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link rel="stylesheet" href="~/Content/lobilist/jquery-ui.min.css">
    <link rel="stylesheet" href="~/Content/lobilist/lobilist.min.css">

    <link rel="stylesheet" href="~/Content/lobilist/lobibox.min.css">
    <link rel="stylesheet" href="~/Content/lobilist/github.css">
    <link rel="stylesheet" href="~/Content/lobilist/demo.css">

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top bg-success">
        <div class="container bg-success">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Работен Календар", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                    <li>
                        @Html.ActionLink("Събития", "Index", "Events")
                    </li>
                    <li>@Html.ActionLink("Календар", "Index", "Calendar")</li>
                    </li>
                    <li>@Html.ActionLink("Задачи", "Index", "Tasks")</li>
</ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            @*<p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>*@
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("ScriptsCalendar", required: false)
    @RenderSection("ScriptsTasks", required: false)
   
</body>
</html>